In [1]:
import numpy as np
np.linspace(-3,3)

array([-3.        , -2.87755102, -2.75510204, -2.63265306, -2.51020408,
       -2.3877551 , -2.26530612, -2.14285714, -2.02040816, -1.89795918,
       -1.7755102 , -1.65306122, -1.53061224, -1.40816327, -1.28571429,
       -1.16326531, -1.04081633, -0.91836735, -0.79591837, -0.67346939,
       -0.55102041, -0.42857143, -0.30612245, -0.18367347, -0.06122449,
        0.06122449,  0.18367347,  0.30612245,  0.42857143,  0.55102041,
        0.67346939,  0.79591837,  0.91836735,  1.04081633,  1.16326531,
        1.28571429,  1.40816327,  1.53061224,  1.65306122,  1.7755102 ,
        1.89795918,  2.02040816,  2.14285714,  2.26530612,  2.3877551 ,
        2.51020408,  2.63265306,  2.75510204,  2.87755102,  3.        ])

In [2]:
array = np.linspace(-3,3,num=100)
array * 10

array([-30.        , -29.39393939, -28.78787879, -28.18181818,
       -27.57575758, -26.96969697, -26.36363636, -25.75757576,
       -25.15151515, -24.54545455, -23.93939394, -23.33333333,
       -22.72727273, -22.12121212, -21.51515152, -20.90909091,
       -20.3030303 , -19.6969697 , -19.09090909, -18.48484848,
       -17.87878788, -17.27272727, -16.66666667, -16.06060606,
       -15.45454545, -14.84848485, -14.24242424, -13.63636364,
       -13.03030303, -12.42424242, -11.81818182, -11.21212121,
       -10.60606061, -10.        ,  -9.39393939,  -8.78787879,
        -8.18181818,  -7.57575758,  -6.96969697,  -6.36363636,
        -5.75757576,  -5.15151515,  -4.54545455,  -3.93939394,
        -3.33333333,  -2.72727273,  -2.12121212,  -1.51515152,
        -0.90909091,  -0.3030303 ,   0.3030303 ,   0.90909091,
         1.51515152,   2.12121212,   2.72727273,   3.33333333,
         3.93939394,   4.54545455,   5.15151515,   5.75757576,
         6.36363636,   6.96969697,   7.57575758,   8.18181818,
         8.78787879,   9.39393939,  10.        ,  10.60606061,
        11.21212121,  11.81818182,  12.42424242,  13.03030303,
        13.63636364,  14.24242424,  14.84848485,  15.45454545,
        16.06060606,  16.66666667,  17.27272727,  17.87878788,
        18.48484848,  19.09090909,  19.6969697 ,  20.3030303 ,
        20.90909091,  21.51515152,  22.12121212,  22.72727273,
        23.33333333,  23.93939394,  24.54545455,  25.15151515,
        25.75757576,  26.36363636,  26.96969697,  27.57575758,
        28.18181818,  28.78787879,  29.39393939,  30.        ])

In [3]:
np.random.randint(50,size=100,high=101)

array([ 68,  53,  54,  64,  80,  94,  74,  74, 100,  93,  90,  64,  76,
        52,  60,  54,  54,  89,  69,  68, 100,  58,  58,  69,  59,  73,
        67,  58,  62,  80,  85,  63,  79,  59,  86,  93,  55,  73,  70,
       100,  99,  67,  86,  61,  59,  59,  78,  69,  75,  88,  77,  50,
        96,  70,  67,  62,  80,  52,  90,  75,  76,  89,  85,  92,  91,
        70,  77,  96,  75,  61,  97,  92,  60,  98,  97,  86,  75,  64,
        72,  59,  91,  73,  51,  85,  72,  59,  68,  65,  77,  86,  69,
        93,  70,  50,  94,  67,  99,  51,  64,  83])

In [5]:
content = np.random.randint(50,size=(50,5),high=101)

In [8]:
import pandas as pd
df1 = pd.DataFrame(data=content,
             index=[f"第{i}號"for i in range(1,51)],
             columns=['國文','英文','數學','地理','歷史'])
df1

       國文   英文   數學   地理   歷史
第1號    76   80   91   77   59
第2號    57   66   99   84   63
第3號    90   75   81   66   64
第4號    73   72   51   50   87
第5號    65   78   88   55   70
第6號    63   82   61   90   58
第7號    78   62   53   58   97
第8號    68   91   83   84   96
第9號    97   99   52   83   99
第10號   51   96   97   80   79
第11號   76   69   74   55   69
第12號   79   78   79   93   52
第13號  100   55   80   52   76
第14號   58   70   88   78   61
第15號   57   74   88   64   61
第16號   77   50   74   51   75
第17號   88   65   84   60   97
第18號   56   81   87   80   75
第19號   80   76   70   91  100
第20號   60   63   93   80   93
第21號   71  100   77   93   90
第22號   76   84   93   80   61
第23號   88   89   79   74  100
第24號   73   52  100   53   65
第25號   86   99   96   97   83
第26號   50   92   84   74   62
第27號   55   97   89   61   60
第28號   88   86   66   69   81
第29號   78   72   52   51   88
第30號   71   91   52   57   51
第31號   55   50   93   56   70
第32號   63   70   73   87   87
第33號   79   57   84   67   72
第34號   71   60   55   74   77
第35號   58   78   67   50   80
第36號   90   58   81   50   99
第37號   77   51   51   95   72
第38號   83   84   91   79   92
第39號   89   57   64   50   71
第40號   54   95   51   99   69
第41號   55   50   95   98   69
第42號   57   88   71   92   70
第43號   63   73   59   93   95
第44號   58   50   69   85   72
第45號   99   64   98   63   74
第46號   88   64   87   64   99
第47號   79   54   84   63   74
第48號   85   88   96   94   82
第49號   53   62   70   93   93
第50號   85   66   90  100   79

In [7]:
df1['國文'] + df1['英文'] + df1['數學'] + df1['地理'] + df1['歷史']

1     383
2     369
3     376
4     333
5     356
6     354
7     348
8     422
9     430
10    403
11    343
12    381
13    363
14    355
15    344
16    327
17    394
18    379
19    417
20    389
21    431
22    394
23    430
24    343
25    461
26    362
27    362
28    390
29    341
30    322
31    324
32    380
33    359
34    337
35    333
36    378
37    346
38    429
39    331
40    368
41    367
42    378
43    383
44    334
45    398
46    402
47    354
48    445
49    371
50    420
dtype: int64

In [9]:
df1.loc["第1號",:]

國文    76
英文    80
數學    91
地理    77
歷史    59
Name: 第1號, dtype: int64

In [10]:
df1.loc["第1號"]

國文    76
英文    80
數學    91
地理    77
歷史    59
Name: 第1號, dtype: int64

In [11]:
df1.loc[["第1號","第5號","第10號"]]

      國文  英文  數學  地理  歷史
第1號   76  80  91  77  59
第5號   65  78  88  55  70
第10號  51  96  97  80  79

In [12]:
df1.iloc[:5]

     國文  英文  數學  地理  歷史
第1號  76  80  91  77  59
第2號  57  66  99  84  63
第3號  90  75  81  66  64
第4號  73  72  51  50  87
第5號  65  78  88  55  70

In [13]:
df1.iloc[-5:]

      國文  英文  數學   地理  歷史
第46號  88  64  87   64  99
第47號  79  54  84   63  74
第48號  85  88  96   94  82
第49號  53  62  70   93  93
第50號  85  66  90  100  79

In [14]:
df1.loc['第10號':'第15號']

       國文  英文  數學  地理  歷史
第10號   51  96  97  80  79
第11號   76  69  74  55  69
第12號   79  78  79  93  52
第13號  100  55  80  52  76
第14號   58  70  88  78  61
第15號   57  74  88  64  61

In [15]:
student_sum = df1.sum(axis=1)
student_mean = df1.mean(axis=1)
df1['總分'] = student_sum
df1['平均'] = student_mean
df1

       國文   英文   數學   地理   歷史   總分    平均
第1號    76   80   91   77   59  383  76.6
第2號    57   66   99   84   63  369  73.8
第3號    90   75   81   66   64  376  75.2
第4號    73   72   51   50   87  333  66.6
第5號    65   78   88   55   70  356  71.2
第6號    63   82   61   90   58  354  70.8
第7號    78   62   53   58   97  348  69.6
第8號    68   91   83   84   96  422  84.4
第9號    97   99   52   83   99  430  86.0
第10號   51   96   97   80   79  403  80.6
第11號   76   69   74   55   69  343  68.6
第12號   79   78   79   93   52  381  76.2
第13號  100   55   80   52   76  363  72.6
第14號   58   70   88   78   61  355  71.0
第15號   57   74   88   64   61  344  68.8
第16號   77   50   74   51   75  327  65.4
第17號   88   65   84   60   97  394  78.8
第18號   56   81   87   80   75  379  75.8
第19號   80   76   70   91  100  417  83.4
第20號   60   63   93   80   93  389  77.8
第21號   71  100   77   93   90  431  86.2
第22號   76   84   93   80   61  394  78.8
第23號   88   89   79   74  100  430  86.0
第24號   73   52  100   53   65  343  68.6
第25號   86   99   96   97   83  461  92.2
第26號   50   92   84   74   62  362  72.4
第27號   55   97   89   61   60  362  72.4
第28號   88   86   66   69   81  390  78.0
第29號   78   72   52   51   88  341  68.2
第30號   71   91   52   57   51  322  64.4
第31號   55   50   93   56   70  324  64.8
第32號   63   70   73   87   87  380  76.0
第33號   79   57   84   67   72  359  71.8
第34號   71   60   55   74   77  337  67.4
第35號   58   78   67   50   80  333  66.6
第36號   90   58   81   50   99  378  75.6
第37號   77   51   51   95   72  346  69.2
第38號   83   84   91   79   92  429  85.8
第39號   89   57   64   50   71  331  66.2
第40號   54   95   51   99   69  368  73.6
第41號   55   50   95   98   69  367  73.4
第42號   57   88   71   92   70  378  75.6
第43號   63   73   59   93   95  383  76.6
第44號   58   50   69   85   72  334  66.8
第45號   99   64   98   63   74  398  79.6
第46號   88   64   87   64   99  402  80.4
第47號   79   54   84   63   74  354  70.8
第48號   85   88   96   94   82  445  89.0
第49號   53   62   70   93   93  371  74.2
第50號   85   66   90  100   79  420  84.0

In [16]:
df2 = df1.sort_values(by='總分',ascending=False)

In [17]:
df2.iloc[:5]

      國文   英文  數學  地理   歷史   總分    平均
第25號  86   99  96  97   83  461  92.2
第48號  85   88  96  94   82  445  89.0
第21號  71  100  77  93   90  431  86.2
第23號  88   89  79  74  100  430  86.0
第9號   97   99  52  83   99  430  86.0

In [18]:
df2.iloc[-5:]

      國文  英文  數學  地理  歷史   總分    平均
第4號   73  72  51  50  87  333  66.6
第39號  89  57  64  50  71  331  66.2
第16號  77  50  74  51  75  327  65.4
第31號  55  50  93  56  70  324  64.8
第30號  71  91  52  57  51  322  64.4

In [19]:
df2['排名'] = df1['總分'].rank(method='first',ascending=False)

In [20]:
df2

       國文   英文   數學   地理   歷史   總分    平均    排名
第25號   86   99   96   97   83  461  92.2   1.0
第48號   85   88   96   94   82  445  89.0   2.0
第21號   71  100   77   93   90  431  86.2   3.0
第23號   88   89   79   74  100  430  86.0   5.0
第9號    97   99   52   83   99  430  86.0   4.0
第38號   83   84   91   79   92  429  85.8   6.0
第8號    68   91   83   84   96  422  84.4   7.0
第50號   85   66   90  100   79  420  84.0   8.0
第19號   80   76   70   91  100  417  83.4   9.0
第10號   51   96   97   80   79  403  80.6  10.0
第46號   88   64   87   64   99  402  80.4  11.0
第45號   99   64   98   63   74  398  79.6  12.0
第22號   76   84   93   80   61  394  78.8  14.0
第17號   88   65   84   60   97  394  78.8  13.0
第28號   88   86   66   69   81  390  78.0  15.0
第20號   60   63   93   80   93  389  77.8  16.0
第1號    76   80   91   77   59  383  76.6  17.0
第43號   63   73   59   93   95  383  76.6  18.0
第12號   79   78   79   93   52  381  76.2  19.0
第32號   63   70   73   87   87  380  76.0  20.0
第18號   56   81   87   80   75  379  75.8  21.0
第36號   90   58   81   50   99  378  75.6  22.0
第42號   57   88   71   92   70  378  75.6  23.0
第3號    90   75   81   66   64  376  75.2  24.0
第49號   53   62   70   93   93  371  74.2  25.0
第2號    57   66   99   84   63  369  73.8  26.0
第40號   54   95   51   99   69  368  73.6  27.0
第41號   55   50   95   98   69  367  73.4  28.0
第13號  100   55   80   52   76  363  72.6  29.0
第27號   55   97   89   61   60  362  72.4  31.0
第26號   50   92   84   74   62  362  72.4  30.0
第33號   79   57   84   67   72  359  71.8  32.0
第5號    65   78   88   55   70  356  71.2  33.0
第14號   58   70   88   78   61  355  71.0  34.0
第47號   79   54   84   63   74  354  70.8  36.0
第6號    63   82   61   90   58  354  70.8  35.0
第7號    78   62   53   58   97  348  69.6  37.0
第37號   77   51   51   95   72  346  69.2  38.0
第15號   57   74   88   64   61  344  68.8  39.0
第24號   73   52  100   53   65  343  68.6  41.0
第11號   76   69   74   55   69  343  68.6  40.0
第29號   78   72   52   51   88  341  68.2  42.0
第34號   71   60   55   74   77  337  67.4  43.0
第44號   58   50   69   85   72  334  66.8  44.0
第35號   58   78   67   50   80  333  66.6  46.0
第4號    73   72   51   50   87  333  66.6  45.0
第39號   89   57   64   50   71  331  66.2  47.0
第16號   77   50   74   51   75  327  65.4  48.0
第31號   55   50   93   56   70  324  64.8  49.0
第30號   71   91   52   57   51  322  64.4  50.0